const apiUrl = "/api/notes";
const el = (id) => document.getElementById(id);
const notesList = el("notes-list"), loading = el("loading-state"), empty = el("empty-state"), error = el("error-state"), modal = el("modal-backdrop"), form = el("note-form");
let editingId = null;
let notes = [];

function showToast(message) { const toast = el("toast"); toast.textContent = message; toast.classList.add("show"); setTimeout(() => toast.classList.remove("show"), 2800); }
function formatDate(value) { return new Intl.DateTimeFormat(undefined, { month:"short", day:"numeric", year:"numeric" }).format(new Date(value)); }
function setState(state) { loading.hidden = state !== "loading"; notesList.hidden = state !== "notes"; empty.hidden = state !== "empty"; error.hidden = state !== "error"; el("notes-region").setAttribute("aria-busy", state === "loading"); }
function escapeHtml(value) { const temp = document.createElement("div"); temp.textContent = value; return temp.innerHTML; }
function showDashboard(user) { el("auth-view").hidden = true; el("dashboard").hidden = false; el("account-actions").hidden = false; el("user-greeting").textContent = `Welcome, ${user.name}`; }
function showAuth() { notes = []; el("dashboard").hidden = true; el("account-actions").hidden = true; el("auth-view").hidden = false; }
function showAuthForm(kind) { const signup = kind === "signup"; el("login-form").hidden = signup; el("signup-form").hidden = !signup; el("auth-kicker").textContent = signup ? "A QUIET CORNER" : "WELCOME BACK"; el("auth-title").innerHTML = signup ? "Begin a place for<br /><em>your thoughts.</em>" : "Your thoughts,<br /><em>waiting for you.</em>"; el("auth-copy").textContent = signup ? "Create an account to keep your notes private." : "Log in to return to your quiet corner."; }
function renderNotes() { notesList.replaceChildren(); if (!notes.length) { setState("empty"); return; } notesList.innerHTML = notes.map(note => `<article class="note-card" tabindex="0" data-id="${note.id}"><h2>${escapeHtml(note.title)}</h2><p class="note-preview">${escapeHtml(note.content || "No content yet.")}</p><footer class="card-footer"><span>${note.updated_at !== note.created_at ? "Updated" : "Created"} ${formatDate(note.updated_at)}</span><span class="card-actions"><button class="card-button" data-action="edit" data-id="${note.id}">Edit</button><button class="card-button delete" data-action="delete" data-id="${note.id}">Delete</button></span></footer></article>`).join(""); setState("notes"); }
async function request(path = "", options = {}) { const response = await fetch(`${apiUrl}${path}`, { headers:{ "Content-Type":"application/json" }, ...options }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || "Something went wrong."); } return response.status === 204 ? null : response.json(); }
async function authRequest(path, options = {}) { const response = await fetch(`/api/auth${path}`, { headers:{ "Content-Type":"application/json" }, ...options }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || "Something went wrong."); } return response.status === 204 ? null : response.json(); }
async function loadNotes() { setState("loading"); try { notes = await request(); renderNotes(); } catch (err) { if (err.message === "Please log in.") return showAuth(); el("error-message").textContent = err.message; setState("error"); } }
function openModal(note = null) { editingId = note?.id ?? null; el("modal-kicker").textContent = note ? "EDIT NOTE" : "NEW NOTE"; el("modal-title").textContent = note ? "Refine your thought." : "Make a little room for a thought."; el("save-button").textContent = note ? "Save Changes" : "Save Note"; el("note-title").value = note?.title ?? ""; el("note-content").value = note?.content ?? ""; el("title-error").textContent = ""; modal.hidden = false; setTimeout(() => el("note-title").focus(), 0); }
function closeModal() { modal.hidden = true; form.reset(); editingId = null; }
async function editNote(id) { try { openModal(await request(`/${id}`)); } catch (err) { showToast(err.message); } }
async function deleteNote(id) { if (!window.confirm("Are you sure you want to delete this note?")) return; try { await request(`/${id}`, { method:"DELETE" }); notes = notes.filter(note => note.id !== Number(id)); renderNotes(); showToast("Note deleted."); } catch (err) { showToast(err.message); } }
async function handleLogin(event) { event.preventDefault(); const errorBox = el("login-error"); errorBox.textContent = ""; try { const user = await authRequest("/login", { method:"POST", body:JSON.stringify({ email:el("login-email").value, password:el("login-password").value }) }); showDashboard(user); await loadNotes(); } catch (err) { errorBox.textContent = err.message; } }
async function handleSignup(event) { event.preventDefault(); const errorBox = el("signup-error"); errorBox.textContent = ""; const password = el("signup-password").value; if (password !== el("signup-confirm-password").value) { errorBox.textContent = "Passwords do not match."; return; } try { await authRequest("/signup", { method:"POST", body:JSON.stringify({ name:el("signup-name").value, email:el("signup-email").value, password, confirm_password:el("signup-confirm-password").value }) }); showAuthForm("login"); el("login-email").value = el("signup-email").value; el("login-error").textContent = "Account created. Please log in."; } catch (err) { errorBox.textContent = err.message; } }
el("new-note-button").onclick = () => openModal(); el("empty-new-note").onclick = () => openModal(); el("close-modal").onclick = closeModal; el("cancel-button").onclick = closeModal; el("retry-button").onclick = loadNotes; el("show-signup").onclick = () => showAuthForm("signup"); el("show-login").onclick = () => showAuthForm("login"); el("login-form").onsubmit = handleLogin; el("signup-form").onsubmit = handleSignup;
el("logout-button").onclick = async () => { await authRequest("/logout", { method:"POST" }); showAuth(); showAuthForm("login"); };
modal.onclick = (event) => { if (event.target === modal) closeModal(); };
notesList.onclick = (event) => { const button = event.target.closest("button[data-action]"); if (!button) return; button.dataset.action === "edit" ? editNote(button.dataset.id) : deleteNote(button.dataset.id); };
form.onsubmit = async (event) => { event.preventDefault(); const title = el("note-title").value.trim(), content = el("note-content").value; if (!title) { el("title-error").textContent = "A title gives this note a home."; return; } const save = el("save-button"), noteId = editingId; save.disabled = true; try { const saved = await request(noteId ? `/${noteId}` : "", { method:noteId ? "PUT" : "POST", body:JSON.stringify({ title, content }) }); notes = noteId ? notes.map(note => note.id === saved.id ? saved : note) : [saved, ...notes]; closeModal(); renderNotes(); showToast(noteId ? "Changes saved." : "Note saved."); } catch (err) { el("title-error").textContent = err.message; } finally { save.disabled = false; save.textContent = noteId ? "Save Changes" : "Save Note"; } };
document.addEventListener("keydown", (event) => { if (event.key === "Escape" && !modal.hidden) closeModal(); });
(async () => { try { const user = await authRequest("/me"); showDashboard(user); loadNotes(); } catch { showAuth(); } })();
